basePath: /api/v1
definitions:
  structs.ChangePasswordRequest:
    properties:
      confirm:
        type: string
      password:
        type: string
    required:
    - confirm
    - password
    type: object
  structs.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  structs.MessageResponse:
    properties:
      message:
        type: string
    type: object
  structs.PasswordChangeTokenRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  structs.TokenRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  structs.TokenResponse:
    properties:
      refreshToken:
        type: string
      token:
        type: string
    type: object
  structs.UserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
host: localhost:5002
info:
  contact:
    email: bsse0807@iit.du.ac.bd
    name: API Support
  description: This is a sample book server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /user/change-password:
    put:
      consumes:
      - application/json
      description: Change Password
      parameters:
      - description: Verify Token
        in: query
        name: verify_token
        required: true
        type: string
      - description: Change Password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structs.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Change the user account password
      tags:
      - user
  /user/refresh-token:
    post:
      consumes:
      - application/json
      description: refreshes the access token
      parameters:
      - description: refresh_token
        format: string
        in: query
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Refresh Token
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: Create User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structs.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Register User
      tags:
      - user
  /user/resend-verify-token:
    post:
      consumes:
      - application/json
      description: Reactivate User
      parameters:
      - description: Create Token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structs.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Resend Verify User Email
      tags:
      - user
  /user/send-password-change-token:
    post:
      consumes:
      - application/json
      description: Change Password
      parameters:
      - description: Create Password Change Token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structs.PasswordChangeTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Send Password Change Email
      tags:
      - user
  /user/token:
    post:
      consumes:
      - application/json
      description: post token
      parameters:
      - description: Create Token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/structs.TokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Generate Token
      tags:
      - token
  /user/verify:
    put:
      consumes:
      - application/json
      description: Activate User
      parameters:
      - description: verify_user
        format: string
        in: query
        name: verify_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/structs.ErrorResponse'
      summary: Verify User
      tags:
      - user
swagger: "2.0"
